// aio_monitor.js — AI Overview Monitor
// Monitors which Google SERPs show AI Overview and whether a target domain is cited.
// Runs as content script on google.com/search pages.

(() => {
  'use strict';

  const STORAGE_KEY = 'seo_aio_data';
  const CONFIG_KEY  = 'seo_aio_config';

  let results   = [];   // captured AIO records
  let isRunning = false;
  let abortRequested = false;
  let queries   = [];   // queue of queries to process
  let currentIdx = 0;
  let targetDomain = '';
  let targetLocation = ''; // cidade/estado para simular localização

  // ── Helpers ────────────────────────────────────────────────────────────────
  function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

  function currentQuery() {
    return new URLSearchParams(window.location.search).get('q') || '';
  }

  function randomDelay(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  // ── AI Overview DOM Extraction ─────────────────────────────────────────────
  // Google's AI Overview uses different containers depending on the layout.
  // Known selectors (2024-2025):
  //   - div[data-attrid="SGE_INTRO_TEXT"]     — early SGE
  //   - div[jsname="s3Eaab"]                  — AI Overview wrapper (confirmed 2024)
  //   - .IVvPP                                — AI Overview card class
  //   - [data-ved] containing "AI-generated"  — accessibility label
  //   - div[data-chunk-index]                 — streamed chunks
  //   - #kp-wp-tab-overview                   — overview tab
  //   - div[jscontroller="MJDnwb"]            — known AIO jscontroller
  //   - div[jscontroller="cGWTCb"]            — alternate AIO jscontroller

  const AIO_SELECTORS = [
    // 2026 — seletores confirmados (Google AI Overview / AI Mode)
    '.Kevs9',           // container principal AIO 2026
    'div.Y3BBE',        // parágrafos gerados pela IA 2026
    '.Nn35F',           // wrapper externo AIO 2026
    'li.jydCyd',        // fontes estruturadas AIO 2026
    // 2025 — seletores confirmados
    'div[jsname="s3Eaab"]',
    'div[data-attrid="SGE_INTRO_TEXT"]',
    '.IVvPP',
    'div[jscontroller="MJDnwb"]',
    'div[jscontroller="cGWTCb"]',
    'div[jscontroller="BiS3nd"]',
    'div[jscontroller="r6MHje"]',
    'div[jsname="yEVEwb"]',
    'div[jsname="LLKzib"]',
    // Fallback: qualquer div com aria-label de AI Overview
    '[aria-label*="visão geral" i]',
    '[aria-label*="AI Overview" i]',
    '[aria-label*="overview" i]',
    '[data-chunk-index]',
    '#kp-wp-tab-overview',
    // Estrutura de card expansível do AIO
    '.vx8Bqd',
    '.zLoFqd',
    '.Tqj3sd',
  ];

  // Heading texts that indicate an AI Overview section
  const AIO_HEADING_TEXTS = [
    'visão geral gerada por ia',
    'visão geral com ia',
    'visão geral',
    'ai overview',
    'gerado pela ia',
    'generated by ai',
    'generative ai',
  ];

  function findAIOContainer() {
    // ── Método 1: seletores conhecidos ────────────────────────────────────────
    for (const sel of AIO_SELECTORS) {
      const els = document.querySelectorAll(sel);
      for (const el of els) {
        const txt = (el.innerText || el.textContent || '').trim();
        if (txt.length > 80) {
          console.log(`[SEO Ext] AIO via seletor: ${sel} (${txt.length} chars)`);
          return el;
        }
      }
    }

    // ── Método 2: qualquer elemento com aria-label contendo "overview" / "visão" ─
    const ariaEls = document.querySelectorAll('[aria-label]');
    for (const el of ariaEls) {
      const label = (el.getAttribute('aria-label') || '').toLowerCase();
      if (label.includes('overview') || label.includes('visão geral') || label.includes('ai')) {
        const txt = (el.innerText || el.textContent || '').trim();
        if (txt.length > 80) {
          console.log(`[SEO Ext] AIO via aria-label="${el.getAttribute('aria-label')}" (${txt.length} chars)`);
          return el;
        }
      }
    }

    // ── Método 3: scan de texto de heading ────────────────────────────────────
    const headings = document.querySelectorAll('h1,h2,h3,[role="heading"]');
    for (const el of headings) {
      const txt = (el.innerText || el.textContent || '').trim().toLowerCase();
      if (txt.length > 80) continue;
      if (AIO_HEADING_TEXTS.some(pat => txt.includes(pat))) {
        let cur = el.parentElement;
        for (let i = 0; i < 8 && cur && cur !== document.body; i++) {
          const content = (cur.innerText || '').trim();
          if (content.length > 100) {
            console.log(`[SEO Ext] AIO via heading "${txt}" → ${cur.tagName}.${cur.className?.split(' ')[0]}`);
            return cur;
          }
          cur = cur.parentElement;
        }
      }
    }

    // ── Método 4: heurística posicional — bloco antes de #rso com ≥2 links ext ─
    const rso = document.querySelector('#rso, #search');
    if (rso) {
      // Irmãos anteriores ao #rso
      let prev = rso.previousElementSibling;
      for (let i = 0; i < 8 && prev; i++) {
        const txt = (prev.innerText || prev.textContent || '').trim();
        const extLinks = prev.querySelectorAll('a[href^="/url"], a[href^="http"]');
        if (txt.length > 150 && extLinks.length >= 2) {
          console.log(`[SEO Ext] AIO via irmão anterior a #rso (${txt.length} chars, ${extLinks.length} links)`);
          return prev;
        }
        prev = prev.previousElementSibling;
      }
      // Filhos do parent antes de #rso
      const parent = rso.parentElement;
      if (parent) {
        const children = [...parent.children];
        const rsoIdx = children.indexOf(rso);
        for (let i = 0; i < rsoIdx; i++) {
          const el = children[i];
          const txt = (el.innerText || el.textContent || '').trim();
          const extLinks = el.querySelectorAll('a[href^="/url"], a[href^="http"]');
          if (txt.length > 150 && extLinks.length >= 2) {
            console.log(`[SEO Ext] AIO via filho[${i}] do parent de #rso (${txt.length} chars)`);
            return el;
          }
        }
      }
    }

    // ── Método 5: qualquer bloco com data-attrid ou data-ved antes do #rso ───
    if (rso) {
      let prev = rso.previousElementSibling;
      while (prev) {
        if (prev.hasAttribute('data-attrid') || prev.hasAttribute('data-ved')) {
          const txt = (prev.innerText || '').trim();
          if (txt.length > 100) {
            console.log(`[SEO Ext] AIO via data-attrid/data-ved (${txt.length} chars)`);
            return prev;
          }
        }
        prev = prev.previousElementSibling;
      }
    }

    console.log('[SEO Ext] AIO: nenhum container detectado nesta SERP');
    return null;
  }

  // ── SERP Position Extraction ───────────────────────────────────────────────
  // Estratégia: iterar sobre blocos de resultado orgânico do DOM e extrair
  // a URL principal de cada um. O Google 2025 usa data-hveid em cada bloco
  // e os links principais são sempre os primeiros <a> com href dentro do h3.
  function resolveGoogleUrl(raw) {
    if (!raw) return '';
    if (raw.startsWith('http') && !raw.includes('google.com/search')) return raw;
    if (raw.startsWith('/url')) {
      try {
        const u = new URL(raw, location.origin);
        return u.searchParams.get('q') || u.searchParams.get('url') || '';
      } catch (_) {}
    }
    return '';
  }

  function isGoogleInternalHost(url) {
    try {
      const h = new URL(url).hostname;
      return h.includes('google.') || h.includes('gstatic.com') ||
             h.includes('googleapis.com') || h.includes('googleusercontent.com') ||
             h.includes('accounts.') || h.includes('youtube.com');
    } catch (_) { return true; }
  }

  function extractSERPPosition() {
    if (!targetDomain) return { position: null, serpUrl: '', debug: [] };

    const d = targetDomain.toLowerCase()
      .replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0];

    const organic = [];   // URLs na ordem que aparecem
    const debugInfo = [];
    const seen = new Set();

    const rso = document.querySelector('#rso, #search, #main');
    const scope = rso || document.body;

    // ── Estratégia principal: rastrear todos os h3 em ordem DOM ──────────────
    // O título de cada resultado orgânico está sempre num <h3>.
    // O href real está no <a> dentro do h3, ou no <a> pai do h3 (.yuRUbf a).
    // Esta abordagem é mais estável que depender de classes CSS obfuscadas.
    const h3Els = [...scope.querySelectorAll('h3')];

    for (const h3 of h3Els) {
      // Pula h3 fora do container de resultados (ex: dentro do AIO, Knowledge Panel)
      if (h3.closest('[data-attrid], .kp-wholepage, .Kevs9, .Nn35F, .IVvPP')) continue;

      // Link dentro do h3
      let a = h3.querySelector('a[href]');

      // Ou o <a> que envolve o h3 (.yuRUbf a)
      if (!a) {
        const parent = h3.closest('a[href]') || h3.parentElement?.querySelector('a[href]');
        if (parent) a = parent;
      }

      // Também tenta o .yuRUbf próximo (container do link no layout moderno)
      if (!a) {
        const yuRUbf = h3.closest('[class]')?.querySelector('.yuRUbf a[href]');
        if (yuRUbf) a = yuRUbf;
      }

      if (!a) continue;

      const raw = a.getAttribute('href') || '';
      const url = resolveGoogleUrl(raw);
      if (!url || isGoogleInternalHost(url)) continue;

      // Filtra links que claramente não são resultados orgânicos
      if (url.includes('google.com') || url.includes('accounts.') ||
          url.includes('support.google') || url.startsWith('#')) continue;

      const key = url.split('?')[0].toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);

      organic.push(url);
      debugInfo.push(`H3#${organic.length}: ${url.substring(0, 90)}`);
    }

    // ── Fallback A: .tF2Cxc e .dURPMd (classes de resultado orgânico 2025-2026) ──
    if (organic.length === 0) {
      const blocks = [...scope.querySelectorAll('.tF2Cxc, .dURPMd, .MjjYud')];
      for (const block of blocks) {
        const a = block.querySelector('.yuRUbf a[href], h3 a[href]');
        if (!a) continue;
        const raw = a.getAttribute('href') || '';
        const url = resolveGoogleUrl(raw);
        if (!url || isGoogleInternalHost(url)) continue;
        const key = url.split('?')[0].toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        organic.push(url);
        debugInfo.push(`FA#${organic.length}: ${url.substring(0, 90)}`);
      }
    }

    // ── Fallback B: data-hveid (layout 2024) ─────────────────────────────────
    if (organic.length === 0 && rso) {
      const blocks = [...rso.querySelectorAll('[data-hveid]')];
      for (const block of blocks) {
        if (block.closest('[data-hveid]:not([data-hveid="' + block.getAttribute('data-hveid') + '"])')) continue;
        const a = block.querySelector('h3 a[href], .yuRUbf a[href]');
        if (!a) continue;
        const raw = a.getAttribute('href') || '';
        const url = resolveGoogleUrl(raw);
        if (!url || isGoogleInternalHost(url)) continue;
        const key = url.split('?')[0].toLowerCase();
        if (seen.has(key)) continue;
        seen.add(key);
        organic.push(url);
        debugInfo.push(`FB#${organic.length}: ${url.substring(0, 90)}`);
      }
    }

    // ── Log de diagnóstico no console ────────────────────────────────────────
    console.log(`[SEO Ext] SERP: ${organic.length} resultados orgânicos | domínio: "${d}"`);
    organic.forEach((u, i) => console.log(`  #${i+1}: ${u}`));

    // ── Busca o domínio na lista ordenada ────────────────────────────────────
    // Compara apenas hostname vs hostname para evitar falsos positivos
    // ex: "move" não pode dar match em "removebg.com"
    for (let i = 0; i < organic.length; i++) {
      let host = '';
      try { host = new URL(organic[i]).hostname.replace(/^www\./, '').toLowerCase(); } catch (_) {}
      // Match exato de hostname, ou hostname termina com .dominio (subdomínio)
      if (host === d || host.endsWith('.' + d) || d.endsWith('.' + host)) {
        return { position: i + 1, serpUrl: organic[i], debug: debugInfo };
      }
    }

    return { position: null, serpUrl: '', debug: debugInfo };
  }

  // Desempacota redirect do Google: /url?q=https://... → https://...
  function unwrapGoogleUrl(raw) {
    if (!raw) return '';
    try {
      const u = new URL(raw, location.origin);
      if (u.hostname.includes('google.') && u.searchParams.has('q')) {
        return u.searchParams.get('q');
      }
    } catch (_) {}
    return raw;
  }

  function extractAIOData(query) {
    const container = findAIOContainer();
    const { position, serpUrl, debug: serpDebug } = extractSERPPosition();

    if (!container) {
      return {
        query,
        appeared: false,
        domainMentioned: false,
        citedUrls: [],
        sources: [],
        text: '',
        textFull: '',
        serpPosition: position,
        serpUrl,
        _debug: { aioFound: false, serpOrganicUrls: serpDebug },
        quadrant: classifyQuery(false, false, position),
        capturedAt: new Date().toISOString(),
      };
    }

    // ── Texto completo ────────────────────────────────────────────────────────
    const textFull = (container.innerText || container.textContent || '')
      .trim()
      .replace(/\s+/g, ' ');
    const text = textFull.substring(0, 2000);

    // ── Fontes estruturadas: { url, title, domain, anchorText } ──────────────
    // O AIO mostra fontes como cards ou inline. Cada <a> com href externo é uma fonte.
    const seenUrls = new Set();
    const sources = [];

    const linkEls = container.querySelectorAll('a[href], a[data-url], a[data-ved]');
    for (const a of linkEls) {
      const raw = a.getAttribute('data-url') || a.href || '';
      const url = unwrapGoogleUrl(raw);
      if (!url || !url.startsWith('http') || url.includes('google.com/search')) continue;

      const key = url.split('?')[0].toLowerCase();
      if (seenUrls.has(key)) continue;
      seenUrls.add(key);

      // Título da fonte: aria-label, title, texto do link, ou h3/span próximo
      let title = a.getAttribute('aria-label') || a.getAttribute('title') || '';
      if (!title) {
        // Tenta pegar o texto do card pai (fontes em cards têm título visível)
        const card = a.closest('[data-ved], [jsname], li, .xDqpzb, .MjjYud');
        if (card) {
          const h = card.querySelector('h3, h4, [role="heading"], .VkpGBb, .yuRUbf');
          title = (h ? h.innerText : a.innerText || '').trim().substring(0, 120);
        } else {
          title = (a.innerText || '').trim().substring(0, 120);
        }
      }

      let domain = '';
      try { domain = new URL(url).hostname.replace(/^www\./, ''); } catch (_) {}

      sources.push({ url, title: title || domain, domain, anchorText: (a.innerText || '').trim().substring(0, 80) });
    }

    // ── citedUrls mantido para compatibilidade ────────────────────────────────
    const citedUrls = sources.map(s => s.url);

    // ── Imagens no bloco AIO ──────────────────────────────────────────────────
    const images = [...container.querySelectorAll('img[src]')]
      .map(img => ({ src: img.src, alt: img.alt || '' }))
      .filter(img => img.src && !img.src.startsWith('data:') && img.src.includes('http'))
      .slice(0, 10);

    // ── Verifica se domínio alvo é citado ────────────────────────────────────
    let domainMentioned = false;
    let brandMentionNoLink = false; // citado no texto mas sem link (menção de marca pura)
    if (targetDomain) {
      const d = targetDomain.toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '');
      const inLinks = citedUrls.some(url => url.toLowerCase().includes(d));
      const inText  = textFull.toLowerCase().includes(d);
      domainMentioned = inText || inLinks;
      // Brand mention sem link: aparece no texto mas não como fonte linkada
      brandMentionNoLink = inText && !inLinks;
    }

    const quadrant = classifyQuery(true, domainMentioned, position);

    return {
      query,
      appeared: true,
      domainMentioned,
      citedUrls,
      sources,
      images,
      text,
      textFull,
      serpPosition: position,
      serpUrl,
      brandMentionNoLink,
      _debug: {
        aioFound: true,
        aioSelector: container.tagName + (container.className ? '.' + container.className.split(' ')[0] : ''),
        aioTextLen: textFull.length,
        sourcesCount: sources.length,
        serpOrganicUrls: serpDebug,
      },
      quadrant,
      capturedAt: new Date().toISOString(),
    };
  }

  // ── Wait for AIO to finish streaming ──────────────────────────────────────
  // AIO text streams in asynchronously. We poll until text is stable for 800ms,
  // or bail early if no AIO found within 2s (most SERPs don't have AIO).
  async function waitForAIOStream(maxWait = 6000) {
    const start = Date.now();
    let lastLen = -1;
    let stableFor = 0;
    let noAIOFor = 0;

    while (Date.now() - start < maxWait) {
      const container = findAIOContainer();
      const curLen = container ? (container.innerText || '').length : 0;

      if (curLen === 0) {
        noAIOFor += 400;
        // Aumentado para 4s: Google AI Overview pode demorar 3-6s para renderizar
        if (noAIOFor >= 4000) return;
      } else {
        noAIOFor = 0;
      }

      if (curLen > 0 && curLen === lastLen) {
        stableFor += 400;
        if (stableFor >= 1000) return; // estável por 1s → stream concluído
      } else {
        stableFor = 0;
        lastLen = curLen;
      }
      await sleep(400);
    }
  }

  // ── Classify query into Q1-Q4 quadrant ────────────────────────────────────
  // Q1 = AIO appeared + domain cited + organic pos ≤ 3  → Protect
  // Q2 = AIO appeared + domain NOT cited + organic pos ≤ 5 → Optimize AIO
  // Q3 = AIO appeared + domain NOT cited + organic pos > 5 → Link Building
  // Q4 = no AIO + organic pos > 5 → Classic SEO
  function classifyQuery(appeared, domainMentioned, serpPosition) {
    if (appeared && domainMentioned && serpPosition && serpPosition <= 3) return 'Q1';
    if (appeared && domainMentioned) return 'Q1';
    if (appeared && !domainMentioned && serpPosition && serpPosition <= 5) return 'Q2';
    if (appeared && !domainMentioned) return 'Q3';
    return 'Q4';
  }

  const QUADRANT_LABELS = {
    Q1: { label: 'Proteger', color: '#34d399', bg: '#065f46' },
    Q2: { label: 'Otimizar AIO', color: '#f59e0b', bg: '#78350f' },
    Q3: { label: 'Link Building', color: '#818cf8', bg: '#1e1b4b' },
    Q4: { label: 'SEO Clássico', color: '#f87171', bg: '#7f1d1d' },
  };

  // ── Compare current run with last saved run ────────────────────────────────
  const LAST_RUN_KEY = 'seo_aio_last_run';

  function saveCurrentAsLastRun(runResults) {
    chrome.storage.local.set({ [LAST_RUN_KEY]: runResults });
  }

  function computeDeltas(currentResults, lastResults) {
    if (!lastResults || !lastResults.length) return null;

    const lastMap = {};
    lastResults.forEach(r => { lastMap[r.query] = r; });

    const deltas = { organic: 0, aio: 0, cited: 0, details: [] };

    currentResults.forEach(cur => {
      const prev = lastMap[cur.query];
      if (!prev) return;

      const aioGained  = cur.appeared && !prev.appeared;
      const aioLost    = !cur.appeared && prev.appeared;
      const citedGained = cur.domainMentioned && !prev.domainMentioned;
      const citedLost   = !cur.domainMentioned && prev.domainMentioned;
      const posGained  = prev.serpPosition && cur.serpPosition && cur.serpPosition < prev.serpPosition;
      const posLost    = prev.serpPosition && cur.serpPosition && cur.serpPosition > prev.serpPosition;
      const posNew     = cur.serpPosition && !prev.serpPosition;

      if (aioGained) deltas.aio++;
      if (aioLost) deltas.aio--;
      if (citedGained) deltas.cited++;
      if (citedLost) deltas.cited--;
      if (posGained || posNew) deltas.organic++;
      if (posLost) deltas.organic--;

      if (aioGained || aioLost || citedGained || citedLost || posGained || posLost) {
        deltas.details.push({ query: cur.query, aioGained, aioLost, citedGained, citedLost, posGained, posLost });
      }
    });

    return deltas;
  }

  // ── Wait for SERP to fully load ────────────────────────────────────────────
  async function waitForSERP(timeoutMs = 12000) {
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      const hasResults = document.querySelector('#rso, #search, .g, .MjjYud, .tF2Cxc');
      if (hasResults) {
        await sleep(600); // layout básico estabilizar
        await waitForAIOStream(4000);
        return true;
      }
      await sleep(300);
    }
    return false;
  }

  // ── Main processing loop ───────────────────────────────────────────────────
  async function processNextQuery() {
    if (abortRequested || currentIdx >= queries.length) {
      finishSession();
      return;
    }

    const q = queries[currentIdx];
    updateStatus(`Processando ${currentIdx + 1}/${queries.length}: "${q}"`, 'running');
    updateProgress(Math.round((currentIdx / queries.length) * 100));

    // Navigate to Google search for this query
    // near= simula localização para buscas locais (ex: "Goiânia, GO")
    const locParam = targetLocation ? `&near=${encodeURIComponent(targetLocation)}` : '';
    const url = `https://www.google.com.br/search?q=${encodeURIComponent(q)}&hl=pt-BR&gl=BR${locParam}`;
    window.location.href = url;
    // The page will reload — the init() function will detect we're mid-session
    // and call processNextQuery() again after the SERP loads
  }

  // Scroll silencioso pelo #rso para forçar render de todos os resultados orgânicos.
  // O Google usa lazy rendering — resultados abaixo da fold podem não estar no DOM.
  // Fazemos isso UMA única vez antes de extrair, sem scroll visível ao usuário.
  async function preloadSERPResults() {
    const rso = document.querySelector('#rso, #search');
    if (!rso) return;

    // Conta h3 antes do scroll para detectar quando novos resultados renderizaram
    let prevH3Count = document.querySelectorAll('h3').length;

    const totalH = document.body.scrollHeight;
    const step = 300;
    let pos = 0;

    while (pos < totalH) {
      pos = Math.min(pos + step, totalH);
      window.scrollTo({ top: pos, behavior: 'instant' });
      await sleep(150); // delay maior para Google renderizar lazy results

      // Se novos h3 apareceram, espera um pouco mais para estabilizar
      const curH3Count = document.querySelectorAll('h3').length;
      if (curH3Count > prevH3Count) {
        prevH3Count = curH3Count;
        await sleep(300);
      }
    }

    window.scrollTo({ top: 0, behavior: 'instant' });
    await sleep(300); // aguarda reflow final antes de extrair
  }

  // Called when page loads and detects a mid-session state
  async function resumeAfterNavigation() {
    const q = queries[currentIdx];
    if (!q) { finishSession(); return; }

    updateStatus(`Aguardando SERP: "${q}"...`, 'running');

    const loaded = await waitForSERP();
    if (!loaded) {
      recordResult({ query: q, appeared: false, domainMentioned: false,
        citedUrls: [], text: 'TIMEOUT', capturedAt: new Date().toISOString() });
    } else {
      // Scroll único para forçar render de todos os resultados orgânicos
      await preloadSERPResults();
      const data = extractAIOData(q);
      recordResult(data);
      addLogItem(q, data.appeared, data.domainMentioned, data.serpPosition, data._debug);
    }

    currentIdx++;
    saveSession();
    updateProgress(Math.round((currentIdx / queries.length) * 100));

    if (abortRequested || currentIdx >= queries.length) {
      finishSession();
      return;
    }

    // Human-like delay before next query (3–7 seconds)
    const delay = randomDelay(3000, 7000);
    updateStatus(`Aguardando ${Math.round(delay/1000)}s antes da próxima...`, 'running');
    await sleep(delay);

    processNextQuery();
  }

  function recordResult(data) {
    results.push(data);
    chrome.storage.local.get(STORAGE_KEY, (d) => {
      const existing = d[STORAGE_KEY] || [];
      const merged = [...existing, data];
      chrome.storage.local.set({ [STORAGE_KEY]: merged });
    });
    updateCounter();
  }

  function finishSession() {
    isRunning = false;
    abortRequested = false;
    hideOverlay();
    updateRunButton(false);
    clearSession();

    const found    = results.filter(r => r.appeared).length;
    const mentioned = results.filter(r => r.domainMentioned).length;
    const withPos  = results.filter(r => r.serpPosition).length;
    updateProgress(100);
    updateStatus(
      `Concluído! ${results.length} queries · ${found} AIO · ${mentioned} citados · ${withPos} na SERP`,
      'done'
    );

    // Save this run as "last run" for delta comparison
    saveCurrentAsLastRun(results);

    // Refresh visibility scores in panel
    renderVisibilityScores();
  }

  // ── Session persistence (survives page navigations) ────────────────────────
  function saveSession() {
    chrome.storage.local.set({
      seo_aio_session: { queries, currentIdx, targetDomain, targetLocation, isRunning: true }
    });
  }

  function clearSession() {
    chrome.storage.local.remove('seo_aio_session');
  }

  function loadSession() {
    return new Promise(resolve => {
      chrome.storage.local.get(['seo_aio_session', STORAGE_KEY, CONFIG_KEY], (data) => {
        results = data[STORAGE_KEY] || [];
        const cfg = data[CONFIG_KEY] || {};
        targetDomain = cfg.domain || '';
        targetLocation = cfg.location || '';
        const session = data['seo_aio_session'];
        resolve(session || null);
      });
    });
  }

  // ── CSV Export ─────────────────────────────────────────────────────────────
  function exportCSV() {
    if (!results.length) { alert('Nenhum resultado capturado ainda.'); return; }

    const header = [
      'query', 'quadrante', 'ai_overview_apareceu', 'dominio_mencionado',
      'mencao_sem_link', 'posicao_serp', 'url_serp',
      'fontes_urls', 'fontes_titulos', 'fontes_dominios',
      'texto_aio_completo', 'capturado_em',
    ];
    const rows = results.map(r => {
      const sources = r.sources || [];
      return [
        r.query,
        r.quadrant || '',
        r.appeared ? 'Sim' : 'Não',
        r.domainMentioned ? 'Sim' : 'Não',
        r.brandMentionNoLink ? 'Sim' : 'Não',
        r.serpPosition || '',
        r.serpUrl || '',
        sources.map(s => s.url).join(' | ') || (r.citedUrls || []).join(' | '),
        sources.map(s => s.title).join(' | '),
        sources.map(s => s.domain).join(' | '),
        r.textFull || r.text || '',
        r.capturedAt || '',
      ].map(v => `"${String(v || '').replace(/"/g, '""')}"`);
    });

    const csv = [header.join(','), ...rows.map(r => r.join(','))].join('\r\n');
    const blob = new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aio_monitor_${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // ── Overlay (blocks accidental interaction during processing) ──────────────
  function showOverlay(text) {
    let ov = document.getElementById('seo-aio-overlay');
    if (!ov) {
      ov = document.createElement('div');
      ov.id = 'seo-aio-overlay';
      ov.style.cssText = 'position:fixed;inset:0;z-index:2147483638;cursor:not-allowed;background:rgba(0,0,0,0.15);pointer-events:all;user-select:none;display:flex;align-items:flex-end;justify-content:flex-start;padding:100px 0 100px 24px;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;';
      document.body.appendChild(ov);
    }
    ov.style.display = 'flex';
  }

  function hideOverlay() {
    const ov = document.getElementById('seo-aio-overlay');
    if (ov) ov.style.display = 'none';
  }

  // ── Floating UI ────────────────────────────────────────────────────────────
  function createUI() {
    if (document.getElementById('seo-aio-panel')) return;

    const style = document.createElement('style');
    style.textContent = `
      #seo-aio-panel {
        position: fixed;
        bottom: 24px;
        left: 24px;
        z-index: 2147483647;
        background: #0f0f10;
        border: 1px solid #2a2a2e;
        border-radius: 14px;
        box-shadow: 0 8px 32px rgba(0,0,0,.5), 0 0 0 1px rgba(255,255,255,.04);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        font-size: 13px;
        color: #e5e7eb;
        width: 270px;
        overflow: hidden;
        user-select: none;
      }
      #seo-aio-header {
        display: flex;
        align-items: center;
        gap: 7px;
        padding: 10px 12px;
        background: #18181b;
        border-bottom: 1px solid #27272a;
        cursor: move;
        font-weight: 600;
        font-size: 12.5px;
        color: #34d399;
      }
      #seo-aio-count {
        margin-left: auto;
        background: #065f46;
        color: #34d399;
        font-size: 10px;
        font-weight: 700;
        padding: 1px 7px;
        border-radius: 10px;
        min-width: 22px;
        text-align: center;
        font-family: 'SF Mono', monospace;
      }
      #seo-aio-body {
        padding: 11px 12px;
        display: flex;
        flex-direction: column;
        gap: 9px;
      }
      .aio-label {
        font-size: 10.5px;
        color: #71717a;
        font-weight: 500;
        margin-bottom: 3px;
      }
      #seo-aio-domain {
        width: 100%;
        padding: 7px 10px;
        border: 1px solid #3f3f46;
        border-radius: 8px;
        background: #18181b;
        color: #e5e7eb;
        font-size: 12px;
        outline: none;
        box-sizing: border-box;
      }
      #seo-aio-domain:focus { border-color: #34d399; }
      #seo-aio-domain::placeholder { color: #52525b; }
      #seo-aio-location {
        width: 100%;
        padding: 7px 10px;
        border: 1px solid #3f3f46;
        border-radius: 8px;
        background: #18181b;
        color: #e5e7eb;
        font-size: 12px;
        outline: none;
        box-sizing: border-box;
      }
      #seo-aio-location:focus { border-color: #818cf8; }
      #seo-aio-location::placeholder { color: #52525b; }
      #seo-aio-queries {
        width: 100%;
        height: 80px;
        padding: 7px 10px;
        border: 1px solid #3f3f46;
        border-radius: 8px;
        background: #18181b;
        color: #e5e7eb;
        font-size: 11.5px;
        outline: none;
        resize: vertical;
        box-sizing: border-box;
        line-height: 1.5;
      }
      #seo-aio-queries:focus { border-color: #34d399; }
      #seo-aio-queries::placeholder { color: #52525b; }
      #seo-aio-run {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 7px;
        width: 100%;
        padding: 8px 10px;
        border: none;
        border-radius: 9px;
        background: #065f46;
        color: #34d399;
        cursor: pointer;
        font-size: 12.5px;
        font-weight: 600;
        transition: background .15s;
      }
      #seo-aio-run:hover { background: #047857; }
      #seo-aio-run.running { background: #7f1d1d; color: #fca5a5; }
      #seo-aio-run.running:hover { background: #991b1b; }
      #seo-aio-progress-wrap {
        display: none;
        flex-direction: column;
        gap: 4px;
      }
      #seo-aio-progress-wrap.visible { display: flex; }
      #seo-aio-progress-bg {
        height: 5px;
        background: #27272a;
        border-radius: 99px;
        overflow: hidden;
      }
      #seo-aio-progress-bar {
        height: 100%;
        width: 0%;
        background: linear-gradient(90deg, #065f46, #34d399);
        border-radius: 99px;
        transition: width .4s ease;
      }
      #seo-aio-progress-label {
        display: flex;
        justify-content: space-between;
        font-size: 10px;
        color: #52525b;
      }
      #seo-aio-progress-pct { color: #34d399; font-weight: 600; font-family: 'SF Mono', monospace; }
      #seo-aio-status {
        font-size: 10.5px;
        color: #71717a;
        text-align: center;
        min-height: 14px;
        line-height: 1.4;
        word-break: break-word;
      }
      #seo-aio-status.running { color: #34d399; }
      #seo-aio-status.done    { color: #34d399; }
      #seo-aio-status.error   { color: #f87171; }
      #seo-aio-log-wrap {
        display: none;
        flex-direction: column;
        gap: 3px;
      }
      #seo-aio-log-wrap.visible { display: flex; }
      .aio-log-label {
        font-size: 10px;
        color: #52525b;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: .06em;
      }
      #seo-aio-log {
        display: flex;
        flex-direction: column;
        gap: 2px;
        max-height: 130px;
        overflow-y: auto;
        scrollbar-width: thin;
        scrollbar-color: #3f3f46 transparent;
      }
      .aio-log-item {
        font-size: 10.5px;
        background: #18181b;
        border-radius: 5px;
        padding: 3px 7px 3px 5px;
        line-height: 1.35;
        border-left: 3px solid #27272a;
        animation: aio-in .2s ease;
        display: flex;
        align-items: center;
        gap: 5px;
      }
      .aio-log-item.found { border-left-color: #34d399; }
      .aio-log-item.found-domain { border-left-color: #f59e0b; }
      .aio-log-item.not-found { border-left-color: #3f3f46; color: #52525b; }
      .aio-log-query { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: #a1a1aa; }
      .aio-log-badge {
        font-size: 9px;
        font-weight: 700;
        padding: 1px 5px;
        border-radius: 4px;
        flex-shrink: 0;
      }
      .badge-yes      { background: #065f46; color: #34d399; }
      .badge-dom      { background: #78350f; color: #f59e0b; }
      .badge-no       { background: #27272a; color: #71717a; }
      .badge-pos      { background: #1e3a5f; color: #60a5fa; min-width: 28px; text-align: center; }
      .badge-pos-none { background: #1c1c1e; color: #3f3f46; }
      @keyframes aio-in {
        from { opacity: 0; transform: translateX(-4px); }
        to   { opacity: 1; transform: translateX(0); }
      }
      .aio-divider { height: 1px; background: #27272a; }
      #seo-aio-actions {
        display: flex;
        gap: 6px;
      }
      #seo-aio-actions button {
        flex: 1;
        padding: 6px 6px;
        border: 1px solid #3f3f46;
        border-radius: 7px;
        background: #27272a;
        color: #a1a1aa;
        cursor: pointer;
        font-size: 11px;
        font-weight: 500;
        transition: all .15s;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 4px;
      }
      #seo-aio-actions button:hover { background: #3f3f46; color: #e5e7eb; }
      #seo-aio-export:hover { border-color: #34d399 !important; color: #34d399 !important; }
      #seo-aio-clear:hover  { border-color: #f87171 !important; color: #f87171 !important; }
      #seo-aio-diag:hover   { border-color: #818cf8 !important; color: #818cf8 !important; }
      #seo-aio-diag-out {
        display: none;
        background: #0d0d10;
        border: 1px solid #27272a;
        border-radius: 8px;
        padding: 8px 10px;
        font-size: 9.5px;
        color: #a1a1aa;
        line-height: 1.6;
        max-height: 200px;
        overflow-y: auto;
        scrollbar-width: thin;
        scrollbar-color: #3f3f46 transparent;
        white-space: pre-wrap;
        word-break: break-all;
        font-family: 'SF Mono', 'Menlo', monospace;
      }
      #seo-aio-diag-out.visible { display: block; }
      .diag-ok  { color: #34d399; }
      .diag-err { color: #f87171; }
      .diag-warn { color: #f59e0b; }
      .aio-spinner {
        width: 10px; height: 10px;
        border: 2px solid rgba(52,211,153,.3);
        border-top-color: #34d399;
        border-radius: 50%;
        animation: aio-spin 1s linear infinite;
        flex-shrink: 0;
      }
      @keyframes aio-spin { to { transform: rotate(360deg); } }
      .aio-info-row {
        display: flex;
        gap: 6px;
        font-size: 10px;
        color: #52525b;
      }
      .aio-stat {
        flex: 1;
        background: #18181b;
        border-radius: 6px;
        padding: 5px 7px;
        text-align: center;
      }
      .aio-stat-num { font-size: 16px; font-weight: 700; color: #e5e7eb; font-family: 'SF Mono', monospace; display: block; }
      .aio-stat-num.green  { color: #34d399; }
      .aio-stat-num.yellow { color: #f59e0b; }

      /* ── Visibility Dashboard ── */
      #seo-vis-section {
        background: #18181b;
        border-radius: 10px;
        padding: 10px 11px;
        display: flex;
        flex-direction: column;
        gap: 8px;
      }
      .vis-header {
        font-size: 10px;
        font-weight: 700;
        color: #52525b;
        text-transform: uppercase;
        letter-spacing: .07em;
        display: flex;
        align-items: center;
        justify-content: space-between;
      }
      .vis-header a {
        color: #818cf8;
        font-size: 9.5px;
        cursor: pointer;
        text-decoration: none;
        font-weight: 600;
        text-transform: none;
        letter-spacing: 0;
      }
      .vis-metric {
        display: flex;
        flex-direction: column;
        gap: 4px;
      }
      .vis-metric-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        font-size: 10.5px;
      }
      .vis-metric-label { color: #a1a1aa; }
      .vis-metric-right {
        display: flex;
        align-items: center;
        gap: 6px;
      }
      .vis-metric-num {
        font-weight: 700;
        color: #e5e7eb;
        font-family: 'SF Mono', monospace;
        font-size: 11px;
      }
      .vis-delta {
        font-size: 9.5px;
        font-weight: 700;
        font-family: 'SF Mono', monospace;
        padding: 1px 5px;
        border-radius: 4px;
      }
      .vis-delta.pos { background: #065f46; color: #34d399; }
      .vis-delta.neg { background: #7f1d1d; color: #fca5a5; }
      .vis-delta.neu { background: #27272a; color: #71717a; }
      .vis-bar-bg {
        height: 5px;
        background: #27272a;
        border-radius: 99px;
        overflow: hidden;
      }
      .vis-bar-fill {
        height: 100%;
        border-radius: 99px;
        transition: width .5s ease;
      }
      .vis-bar-fill.organic { background: linear-gradient(90deg, #1e3a5f, #60a5fa); }
      .vis-bar-fill.aio     { background: linear-gradient(90deg, #065f46, #34d399); }
      .vis-bar-fill.cited   { background: linear-gradient(90deg, #78350f, #f59e0b); }
      .vis-quadrants {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 4px;
        margin-top: 2px;
      }
      .vis-q {
        border-radius: 6px;
        padding: 5px 7px;
        font-size: 9.5px;
        display: flex;
        align-items: center;
        justify-content: space-between;
      }
      .vis-q-count {
        font-weight: 700;
        font-family: 'SF Mono', monospace;
        font-size: 13px;
      }
      .vis-no-data {
        font-size: 10.5px;
        color: #52525b;
        text-align: center;
        padding: 4px 0;
      }
      .vis-open-dash {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 5px;
        width: 100%;
        padding: 7px;
        border: 1px solid #3f3f46;
        border-radius: 8px;
        background: transparent;
        color: #818cf8;
        font-size: 11px;
        font-weight: 600;
        cursor: pointer;
        transition: all .15s;
        margin-top: 2px;
      }
      .vis-open-dash:hover { background: #1e1b4b; border-color: #818cf8; }
    `;
    document.head.appendChild(style);

    const panel = document.createElement('div');
    panel.id = 'seo-aio-panel';
    panel.innerHTML = `
      <div id="seo-aio-header">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <circle cx="12" cy="12" r="3"/><path d="M12 1v4M12 19v4M4.22 4.22l2.83 2.83M16.95 16.95l2.83 2.83M1 12h4M19 12h4M4.22 19.78l2.83-2.83M16.95 7.05l2.83-2.83"/>
        </svg>
        <span>AI Overview Monitor</span>
        <span id="seo-aio-count">0</span>
      </div>
      <div id="seo-aio-body">

        <div id="seo-vis-section">
          <div class="vis-header">
            <span>Visibilidade</span>
            <a id="vis-open-btn" title="Abrir dashboard completo">Ver detalhes →</a>
          </div>
          <div id="seo-vis-content">
            <div class="vis-no-data">Rode uma análise para ver sua visibilidade.</div>
          </div>
        </div>

        <div>
          <div class="aio-label">Domínio a monitorar</div>
          <input id="seo-aio-domain" type="text" placeholder="ex: seusite.com.br" autocomplete="off" spellcheck="false"/>
        </div>

        <div>
          <div class="aio-label">Localização (busca local)</div>
          <input id="seo-aio-location" type="text" placeholder="ex: Goiânia, GO" autocomplete="off" spellcheck="false"/>
        </div>

        <div>
          <div class="aio-label">Queries (uma por linha)</div>
          <textarea id="seo-aio-queries" placeholder="o que é seo&#10;como aparecer no google&#10;marketing digital para empresas"></textarea>
        </div>

        <button id="seo-aio-run">Iniciar monitoramento</button>

        <div id="seo-aio-progress-wrap">
          <div id="seo-aio-progress-bg">
            <div id="seo-aio-progress-bar"></div>
          </div>
          <div id="seo-aio-progress-label">
            <span id="seo-aio-status"></span>
            <span id="seo-aio-progress-pct">0%</span>
          </div>
        </div>

        <div id="seo-aio-stats-wrap" style="display:none;">
          <div class="aio-info-row">
            <div class="aio-stat">
              <span id="seo-aio-stat-total" class="aio-stat-num">0</span>
              Processadas
            </div>
            <div class="aio-stat">
              <span id="seo-aio-stat-found" class="aio-stat-num green">0</span>
              Com AIO
            </div>
            <div class="aio-stat">
              <span id="seo-aio-stat-domain" class="aio-stat-num yellow">0</span>
              Mencionam
            </div>
          </div>
        </div>

        <div id="seo-aio-log-wrap">
          <div class="aio-log-label">Resultados</div>
          <div id="seo-aio-log"></div>
        </div>

        <div class="aio-divider"></div>

        <div id="seo-aio-actions">
          <button id="seo-aio-export">
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/>
              <line x1="12" y1="15" x2="12" y2="3"/>
            </svg>
            CSV
          </button>
          <button id="seo-aio-diag" title="Diagnóstico desta SERP">
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/>
              <line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
            Diagnóstico
          </button>
          <button id="seo-aio-clear">
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/>
              <path d="M10 11v6M14 11v6M9 6V4h6v2"/>
            </svg>
            Limpar
          </button>
        </div>
        <div id="seo-aio-diag-out"></div>

      </div>
    `;
    document.body.appendChild(panel);

    document.getElementById('seo-aio-run').addEventListener('click', onRunClick);
    document.getElementById('seo-aio-export').addEventListener('click', exportCSV);
    document.getElementById('seo-aio-clear').addEventListener('click', onClearClick);
    document.getElementById('seo-aio-diag').addEventListener('click', runDiagnostics);

    // Persist domain input
    const domainInput = document.getElementById('seo-aio-domain');
    domainInput.value = targetDomain;
    domainInput.addEventListener('input', () => {
      targetDomain = domainInput.value.trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '');
      chrome.storage.local.set({ [CONFIG_KEY]: { domain: targetDomain, location: targetLocation } });
    });

    // Persist location input
    const locationInput = document.getElementById('seo-aio-location');
    locationInput.value = targetLocation;
    locationInput.addEventListener('input', () => {
      targetLocation = locationInput.value.trim();
      chrome.storage.local.set({ [CONFIG_KEY]: { domain: targetDomain, location: targetLocation } });
    });

    // Auto-import queries from Search Console extractor
    chrome.storage.local.get('sc_queries', (data) => {
      const scQueries = data['sc_queries'];
      if (!scQueries || !scQueries.length) return;
      const textarea = document.getElementById('seo-aio-queries');
      if (!textarea || textarea.value.trim()) return; // não sobrescreve se já tem conteúdo
      textarea.value = scQueries.join('\n');
      showScImportBadge(scQueries.length);
    });

    makeDraggable(panel, document.getElementById('seo-aio-header'));
    updateCounter();

    // Open dashboard in new tab
    document.getElementById('vis-open-btn').addEventListener('click', () => {
      chrome.runtime.sendMessage({ action: 'openDashboard' });
    });

    // Render visibility scores from existing storage
    renderVisibilityScores();
  }

  function runDiagnostics() {
    const out = document.getElementById('seo-aio-diag-out');
    if (!out) return;

    // Toggle: se já está visível, fecha
    if (out.classList.contains('visible')) {
      out.classList.remove('visible');
      return;
    }

    const lines = [];
    const ok  = s => `<span class="diag-ok">✓ ${s}</span>`;
    const err = s => `<span class="diag-err">✗ ${s}</span>`;
    const warn = s => `<span class="diag-warn">⚠ ${s}</span>`;

    // ── 1. Domínio configurado ────────────────────────────────────────────────
    const dom = targetDomain || (document.getElementById('seo-aio-domain')?.value || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '');
    lines.push(`<b>Domínio:</b> ${dom || err('não configurado')}`);
    const loc = targetLocation || (document.getElementById('seo-aio-location')?.value || '').trim();
    if (loc) lines.push(`<b>Localização:</b> ${loc}`);

    lines.push('');

    // ── 2. AIO ────────────────────────────────────────────────────────────────
    lines.push('<b>── AI Overview ──</b>');
    const aioContainer = findAIOContainer();
    if (aioContainer) {
      const sel = aioContainer.id ? `#${aioContainer.id}` :
        (aioContainer.className ? `.${aioContainer.className.trim().split(/\s+/)[0]}` : aioContainer.tagName);
      const txt = (aioContainer.innerText || '').trim();
      const linkCount = aioContainer.querySelectorAll('a[href], a[href^="/url"]').length;
      lines.push(ok(`AIO detectado via: ${sel}`));
      lines.push(`  Texto: ${txt.length} chars`);
      lines.push(`  Links internos: ${linkCount}`);
      // Fontes externas
      const extLinks = [...aioContainer.querySelectorAll('a[href], a[data-url]')]
        .map(a => unwrapGoogleUrl(a.getAttribute('data-url') || a.href || ''))
        .filter(u => u.startsWith('http') && !u.includes('google.com/search'));
      lines.push(`  Fontes externas: ${extLinks.length}`);
      extLinks.slice(0, 5).forEach(u => lines.push(`    · ${u.substring(0, 70)}`));
      if (dom) {
        const d = dom.replace(/^https?:\/\//, '').replace(/^www\./, '');
        const found = extLinks.some(u => u.toLowerCase().includes(d));
        const inText = txt.toLowerCase().includes(d);
        lines.push(found ? ok(`Domínio citado como fonte`) : inText ? warn(`Domínio no texto (sem link)`) : err(`Domínio NÃO encontrado no AIO`));
      }
    } else {
      lines.push(warn('AIO não detectado nesta SERP'));
      lines.push('  Seletores testados:');
      AIO_SELECTORS.forEach(sel => {
        const el = document.querySelector(sel);
        if (el) lines.push(warn(`  encontrou ${sel} mas sem texto suficiente`));
      });
    }

    lines.push('');

    // ── 3. SERP Orgânica ──────────────────────────────────────────────────────
    lines.push('<b>── SERP Orgânica ──</b>');

    // Containers disponíveis
    const rsoEl = document.querySelector('#rso');
    const searchEl = document.querySelector('#search');
    lines.push(rsoEl ? ok('#rso encontrado') : warn('#rso não encontrado'));
    lines.push(searchEl ? ok('#search encontrado') : warn('#search não encontrado'));

    // h3 como estratégia principal
    const rsoForDiag = rsoEl || searchEl || document.querySelector('#main') || document.body;
    const allH3 = [...rsoForDiag.querySelectorAll('h3')];
    const h3WithLinks = allH3.filter(h3 => {
      if (h3.closest('[data-attrid], .kp-wholepage, .Kevs9, .Nn35F, .IVvPP')) return false;
      return !!(h3.querySelector('a[href]') || h3.closest('a[href]') || h3.parentElement?.querySelector('a[href]'));
    });
    lines.push(`  H3 totais na página: ${allH3.length}`);
    lines.push(`  H3 com link (candidatos orgânicos): ${h3WithLinks.length}`);

    // Classes de bloco orgânico
    const tF2Cxc = rsoForDiag.querySelectorAll('.tF2Cxc').length;
    const dURPMd = rsoForDiag.querySelectorAll('.dURPMd').length;
    const MjjYud = rsoForDiag.querySelectorAll('.MjjYud').length;
    const hveidBlocks = rsoForDiag.querySelectorAll('[data-hveid]').length;
    lines.push(`  .tF2Cxc: ${tF2Cxc} | .dURPMd: ${dURPMd} | .MjjYud: ${MjjYud} | [data-hveid]: ${hveidBlocks}`);

    const { position, serpUrl, debug: serpDebug } = extractSERPPosition();
    lines.push(`  URLs orgânicas extraídas: ${serpDebug.length}`);
    serpDebug.slice(0, 12).forEach(l => lines.push(`  ${l}`));
    if (serpDebug.length > 12) lines.push(`  ... e mais ${serpDebug.length - 12}`);

    if (dom) {
      if (position) {
        lines.push(ok(`Domínio na posição #${position}`));
        lines.push(`  URL: ${serpUrl.substring(0, 70)}`);
      } else if (serpDebug.length > 0) {
        lines.push(err(`"${dom}" não encontrado nas ${serpDebug.length} URLs orgânicas`));
      } else {
        lines.push(warn('Sem URLs orgânicas — SERP pode estar carregando ou layout diferente'));
        // Mostra estrutura bruta para diagnóstico
        if (rsoForDiag) {
          const firstChildren = [...rsoForDiag.children].slice(0, 5);
          firstChildren.forEach((c, i) => {
            lines.push(`  filho[${i}]: ${c.tagName}.${(c.className||'').split(' ')[0]} data-hveid=${c.getAttribute('data-hveid')||'—'}`);
          });
        }
      }
    }

    out.innerHTML = lines.join('\n');
    out.classList.add('visible');
  }

  function onRunClick() {
    if (isRunning) {
      abortRequested = true;
      updateStatus('Parando após esta query...', 'running');
      return;
    }

    const rawQueries = (document.getElementById('seo-aio-queries')?.value || '')
      .split('\n')
      .map(q => q.trim())
      .filter(q => q.length > 1);

    if (!rawQueries.length) {
      updateStatus('Cole ao menos uma query.', 'error');
      return;
    }

    targetDomain = (document.getElementById('seo-aio-domain')?.value || '').trim()
      .toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '');
    targetLocation = (document.getElementById('seo-aio-location')?.value || '').trim();

    queries = rawQueries;
    currentIdx = 0;
    isRunning = true;
    abortRequested = false;
    results = [];

    saveSession();
    updateRunButton(true);
    showProgressArea(true);
    showOverlay();
    clearLog();
    updateStats();
    processNextQuery();
  }

  function onClearClick() {
    if (!confirm('Limpar todos os resultados do AI Overview Monitor?')) return;
    chrome.storage.local.remove([STORAGE_KEY, 'seo_aio_session'], () => {
      results = [];
      updateCounter();
      clearLog();
      showProgressArea(false);
      updateStatus('', '');
      updateProgress(0);
      hideStatsPanel();
    });
  }

  // ── UI Updaters ────────────────────────────────────────────────────────────
  function updateRunButton(running) {
    const btn = document.getElementById('seo-aio-run');
    if (!btn) return;
    if (running) {
      btn.classList.add('running');
      btn.innerHTML = `<span class="aio-spinner"></span> Parar monitoramento`;
    } else {
      btn.classList.remove('running');
      btn.innerHTML = 'Iniciar monitoramento';
    }
  }

  function showProgressArea(visible) {
    const pw = document.getElementById('seo-aio-progress-wrap');
    const lw = document.getElementById('seo-aio-log-wrap');
    if (pw) pw.classList.toggle('visible', visible);
    if (lw) lw.classList.toggle('visible', visible);
  }

  function hideStatsPanel() {
    const sw = document.getElementById('seo-aio-stats-wrap');
    if (sw) sw.style.display = 'none';
  }

  function updateProgress(pct) {
    const bar = document.getElementById('seo-aio-progress-bar');
    const lbl = document.getElementById('seo-aio-progress-pct');
    if (bar) bar.style.width = pct + '%';
    if (lbl) lbl.textContent = pct + '%';
  }

  function updateStatus(msg, state) {
    const el = document.getElementById('seo-aio-status');
    if (!el) return;
    el.textContent = msg;
    el.className = state || '';
  }

  function updateCounter() {
    const el = document.getElementById('seo-aio-count');
    if (el) el.textContent = results.length;
  }

  function updateStats() {
    const sw = document.getElementById('seo-aio-stats-wrap');
    if (sw) sw.style.display = 'block';
    const tot = document.getElementById('seo-aio-stat-total');
    const fnd = document.getElementById('seo-aio-stat-found');
    const dom = document.getElementById('seo-aio-stat-domain');
    if (tot) tot.textContent = results.length;
    if (fnd) fnd.textContent = results.filter(r => r.appeared).length;
    if (dom) dom.textContent = results.filter(r => r.domainMentioned).length;
  }

  function addLogItem(query, appeared, domainMentioned, serpPosition, debugData) {
    const log = document.getElementById('seo-aio-log');
    if (!log) return;

    const cls = domainMentioned ? 'found-domain' : appeared ? 'found' : 'not-found';

    const aioBadge = domainMentioned
      ? '<span class="aio-log-badge badge-dom">CITADO</span>'
      : appeared
        ? '<span class="aio-log-badge badge-yes">AIO</span>'
        : '<span class="aio-log-badge badge-no">sem AIO</span>';

    const posBadge = serpPosition
      ? `<span class="aio-log-badge badge-pos" title="Posição orgânica">#${serpPosition}</span>`
      : '<span class="aio-log-badge badge-pos-none">sem pos.</span>';

    const item = document.createElement('div');
    item.className = `aio-log-item ${cls}`;
    item.style.flexDirection = 'column';
    item.style.alignItems = 'flex-start';
    item.style.gap = '3px';

    const topRow = document.createElement('div');
    topRow.style.cssText = 'display:flex;align-items:center;gap:5px;width:100%;';
    topRow.innerHTML = `${aioBadge}${posBadge}<span class="aio-log-query" title="${query}">${query}</span>`;
    item.appendChild(topRow);

    // Debug row: mostra quantas URLs orgânicas foram encontradas e se AIO foi detectado
    if (debugData) {
      const dbg = document.createElement('div');
      dbg.style.cssText = 'font-size:9px;color:#52525b;padding-left:2px;line-height:1.4;';
      const serpCount = (debugData.serpOrganicUrls || []).length;
      const aioInfo = debugData.aioFound
        ? `AIO: ${debugData.aioTextLen || 0} chars, ${debugData.sourcesCount || 0} fontes`
        : 'AIO: não detectado';
      dbg.textContent = `SERP: ${serpCount} resultados org. | ${aioInfo}`;
      item.appendChild(dbg);

      // Se zero resultados orgânicos, mostra alerta
      if (serpCount === 0) {
        const warn = document.createElement('div');
        warn.style.cssText = 'font-size:9px;color:#f59e0b;padding-left:2px;';
        warn.textContent = '⚠ SERP não lida — verifique seletores DOM';
        item.appendChild(warn);
      }
    }

    log.appendChild(item);
    log.scrollTop = log.scrollHeight;

    updateStats();
    updateCounter();
  }

  function clearLog() {
    const log = document.getElementById('seo-aio-log');
    if (log) log.innerHTML = '';
  }

  function showScImportBadge(count) {
    // Remove badge anterior se existir
    const old = document.getElementById('seo-aio-sc-badge');
    if (old) old.remove();

    const badge = document.createElement('div');
    badge.id = 'seo-aio-sc-badge';
    badge.style.cssText = `
      font-size:10px; color:#818cf8; background:#1e1b4b;
      border-radius:6px; padding:4px 9px; text-align:center;
      border:1px solid #312e81; line-height:1.4;
    `;
    badge.textContent = `↑ ${count} queries importadas do Search Console`;

    // Insere antes do botão Iniciar
    const runBtn = document.getElementById('seo-aio-run');
    if (runBtn) runBtn.parentNode.insertBefore(badge, runBtn);
  }

  // ── Visibility Score 0-100 ────────────────────────────────────────────────
  // Weights: SERP presence 25% · AIO appearance 35% · AIO cited 30% · no-link mention 10%
  function computeVisibilityScore(data) {
    if (!data.length) return 0;
    const n = data.length;
    const wPos  = data.filter(r => r.serpPosition).length / n;
    const wAIO  = data.filter(r => r.appeared).length / n;
    const wCite = data.filter(r => r.domainMentioned).length / n;
    const wBrand = data.filter(r => r.brandMentionNoLink).length / n;
    return Math.round((wPos * 25 + wAIO * 35 + wCite * 30 + wBrand * 10) * 100) / 100;
  }

  // ── Visibility Score Dashboard ─────────────────────────────────────────────
  function renderVisibilityScores() {
    const container = document.getElementById('seo-vis-content');
    if (!container) return;

    // If results not in memory, load from storage
    function doRender(data) {
      if (!data.length) {
        container.innerHTML = '<div class="vis-no-data">Rode uma análise para ver sua visibilidade.</div>';
        return;
      }

      const total       = data.length;
      const withPos     = data.filter(r => r.serpPosition).length;
      const withAIO     = data.filter(r => r.appeared).length;
      const cited       = data.filter(r => r.domainMentioned).length;
      const brandOnly   = data.filter(r => r.brandMentionNoLink).length;

      const pctOrganic  = total ? Math.round((withPos / total) * 100) : 0;
      const pctAIO      = total ? Math.round((withAIO / total) * 100) : 0;
      const pctCited    = total ? Math.round((cited / total) * 100) : 0;
      const aioRate     = pctAIO; // % de SERPs com AIO no conjunto
      const visScore    = computeVisibilityScore(data);

      const qCounts = { Q1: 0, Q2: 0, Q3: 0, Q4: 0 };
      data.forEach(r => { if (r.quadrant) qCounts[r.quadrant]++; });

      chrome.storage.local.get(LAST_RUN_KEY, (stored) => {
        const lastRun = stored[LAST_RUN_KEY] || [];
        const prevTotal   = lastRun.length;
        const prevOrganic = lastRun.filter(r => r.serpPosition).length;
        const prevAIO     = lastRun.filter(r => r.appeared).length;
        const prevCited   = lastRun.filter(r => r.domainMentioned).length;

        const deltaOrganic = prevTotal ? withPos - prevOrganic : null;
        const deltaAIO     = prevTotal ? withAIO - prevAIO : null;
        const deltaCited   = prevTotal ? cited - prevCited : null;

        function deltaHTML(d) {
          if (d === null) return '';
          const cls = d > 0 ? 'pos' : d < 0 ? 'neg' : 'neu';
          const sign = d > 0 ? '▲+' : d < 0 ? '▼' : '=';
          return `<span class="vis-delta ${cls}">${sign}${d}</span>`;
        }

        function metricHTML(label, num, tot, pct, delta, barClass) {
          return `
            <div class="vis-metric">
              <div class="vis-metric-header">
                <span class="vis-metric-label">${label}</span>
                <div class="vis-metric-right">
                  <span class="vis-metric-num">${num}/${tot}</span>
                  ${deltaHTML(delta)}
                </div>
              </div>
              <div class="vis-bar-bg">
                <div class="vis-bar-fill ${barClass}" style="width:${pct}%"></div>
              </div>
            </div>`;
        }

        const qHTML = Object.entries(QUADRANT_LABELS).map(([q, cfg]) => `
          <div class="vis-q" style="background:${cfg.bg}20;border:1px solid ${cfg.bg}40;">
            <span style="color:${cfg.color};font-size:9px;font-weight:600;">${q} ${cfg.label}</span>
            <span class="vis-q-count" style="color:${cfg.color};">${qCounts[q]}</span>
          </div>`).join('');

        const scoreColor = visScore >= 60 ? '#34d399' : visScore >= 35 ? '#f59e0b' : '#f87171';
        const aioRateColor = aioRate >= 50 ? '#34d399' : aioRate >= 25 ? '#f59e0b' : '#f87171';

        container.innerHTML = `
          <div style="display:flex;align-items:center;justify-content:space-between;padding:4px 0 6px;">
            <span style="font-size:10px;color:#52525b;font-weight:700;text-transform:uppercase;letter-spacing:.06em;">Score de Visibilidade</span>
            <span style="font-size:22px;font-weight:800;font-family:'SF Mono',monospace;color:${scoreColor};">${visScore}</span>
          </div>
          <div style="display:flex;align-items:center;justify-content:space-between;padding:2px 0 8px;border-bottom:1px solid #27272a;margin-bottom:6px;">
            <span style="font-size:9.5px;color:#52525b;">AIO aparece em <b style="color:${aioRateColor};">${aioRate}%</b> das SERPs · Menção sem link: <b style="color:#818cf8;">${brandOnly}</b></span>
          </div>
          ${metricHTML('Presença Orgânica', withPos, total, pctOrganic, deltaOrganic, 'organic')}
          ${metricHTML('IA do Google (AIO)', withAIO, total, pctAIO, deltaAIO, 'aio')}
          ${metricHTML('Citado pela IA', cited, total, pctCited, deltaCited, 'cited')}
          <div class="vis-quadrants">${qHTML}</div>
        `;
      });
    }

    if (results.length) {
      doRender(results);
    } else {
      chrome.storage.local.get(STORAGE_KEY, (d) => doRender(d[STORAGE_KEY] || []));
    }
  }

  function makeDraggable(el, handle) {
    let startX, startY, origX, origY;
    handle.addEventListener('mousedown', (e) => {
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      startX = e.clientX; startY = e.clientY;
      origX = rect.left; origY = rect.top;
      el.style.left = origX + 'px'; el.style.top = origY + 'px';
      el.style.bottom = 'auto'; el.style.right = 'auto';
      const onMove = (e) => {
        el.style.left = Math.max(0, origX + e.clientX - startX) + 'px';
        el.style.top  = Math.max(0, origY + e.clientY - startY) + 'px';
      };
      const onUp = () => {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onUp);
      };
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onUp);
    });
  }

  // ── Init ───────────────────────────────────────────────────────────────────
  async function init() {
    if (!window.location.hostname.includes('google.')) return;
    if (!window.location.pathname.startsWith('/search') &&
        window.location.pathname !== '/') return;

    // Só ativa se o toggle estiver ligado
    const stored = await new Promise(r => chrome.storage.local.get('seo_tools_enabled', r));
    if (!stored.seo_tools_enabled?.aio) return;

    createUI();

    // Check if we're mid-session (page reloaded as part of query processing)
    const session = await loadSession();
    if (session && session.isRunning) {
      queries       = session.queries;
      currentIdx    = session.currentIdx;
      targetDomain  = session.targetDomain || '';
      targetLocation = session.targetLocation || '';
      isRunning     = true;

      // Restore domain and location inputs
      const domainInput = document.getElementById('seo-aio-domain');
      if (domainInput) domainInput.value = targetDomain;
      const locationInput = document.getElementById('seo-aio-location');
      if (locationInput) locationInput.value = targetLocation;

      updateRunButton(true);
      showProgressArea(true);
      showOverlay();

      // Check if we just landed on the query we need to process
      const expectedQuery = queries[currentIdx];
      const actualQuery = currentQuery();

      // Normaliza: decodifica URI, remove sinais de +, lowercase, trim
      function normalizeQ(s) {
        try { s = decodeURIComponent(s.replace(/\+/g, ' ')); } catch (_) {}
        return s.toLowerCase().trim();
      }
      const normExpected = normalizeQ(expectedQuery);
      const normActual   = normalizeQ(actualQuery);
      // Match se os primeiros 15 chars coincidem OU se a query inteira está contida
      const isMatch = normActual.includes(normExpected.substring(0, 15)) ||
                      normExpected.includes(normActual.substring(0, 15));

      if (expectedQuery && actualQuery && isMatch) {
        resumeAfterNavigation();
      } else {
        // We're on a different URL — go to the right query
        processNextQuery();
      }
    } else {
      // Not mid-session — re-render scores with now-loaded results
      renderVisibilityScores();
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();
